name: 'Setup Python for R2R Full'
description: 'Sets up Python and installs R2R dependencies for full installation'
inputs:
  os:
    description: 'Operating system'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install R2R CLI & Python SDK
      shell: bash
      run: |
        pip install r2r
