name: 'Run SDK Chunks Tests'
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      # Run the chunks tests - adjust order as needed
      # This is similar to the documents tests, just calling different test functions

      - name: List chunks (SDK)
        shell: bash
        run: poetry run python tests/integration/runner_chunks.py test_list_chunks

      - name: Retrieve chunk (SDK)
        shell: bash
        run: poetry run python tests/integration/runner_chunks.py test_retrieve_chunk

      - name: Update chunk (SDK)
        shell: bash
        run: poetry run python tests/integration/runner_chunks.py test_update_chunk

      - name: Delete chunk (SDK)
        shell: bash
        run: poetry run python tests/integration/runner_chunks.py test_delete_chunk

      - name: Search chunks (SDK)
        shell: bash
        run: poetry run python tests/integration/runner_chunks.py test_search_chunks

      - name: List chunks with pagination (SDK)
        shell: bash
        run: poetry run python tests/integration/runner_chunks.py test_list_chunks_with_pagination

      - name: Retrieve chunk not found (SDK)
        shell: bash
        run: poetry run python tests/integration/runner_chunks.py test_retrieve_chunk_not_found

      - name: Unauthorized chunk access (SDK)
        shell: bash
        run: poetry run python tests/integration/runner_chunks.py test_unauthorized_chunk_access
