name: 'Start R2R Server'
description: 'Starts the R2R server'
runs:
  using: "composite"
  steps:
    - name: Ingest sample file (CLI)
      working-directory: ./py
      run: poetry run python tests/integration/harness_cli.py test_ingest_sample_file_cli

    - name: Document overview (CLI)
      working-directory: ./py
      run: poetry run python tests/integration/harness_cli.py test_document_overview_sample_file_cli

    - name: Document chunks (CLI)
      working-directory: ./py
      run: poetry run python tests/integration/harness_cli.py test_document_chunks_sample_file_cli

    - name: Delete and reingest (CLI)
      working-directory: ./py
      run: poetry run python tests/integration/harness_cli.py test_delete_and_reingest_sample_file_cli


    - name: Update file (CLI)
      working-directory: ./py
      run: poetry run python tests/integration/harness_cli.py test_update_file_cli
