coverage:
  status:
    project:
      default:
        threshold: 100%
  parsers:
    gcov:
      branch_detection:
        conditional: yes
        loop: yes
        method: no
        macro: no

  flags:
    python:
      paths:
        - py/
    javascript:
      paths:
        - js/
    go:
      paths:
        - go/
