name: 'Run CLI Retrieval Tests'
description: 'Runs CLI retrieval tests for R2R'
runs:
  using: "composite"
  steps:
    # Ingest the sample file via the CLI for later tests
    - name: Ingest sample file (CLI)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_cli.py test_ingest_sample_file_cli

    - name: Vector search the sample file (CLI)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_cli.py test_vector_search_sample_file_filter_cli

    - name: RAG over sample file (CLI)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_cli.py test_rag_response_sample_file_cli

    - name: RAG streaming response (CLI)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_cli.py test_rag_response_stream_sample_file_cli
