name: 'Run SDK Auth Tests'
description: 'Runs SDK authentication tests for R2R'
runs:
  using: "composite"
  steps:
    - name: Ingest zerox document
      working-directory: ./py
      shell: bash
      run: poetry run python core/examples/scripts/run_ingest_with_zerox.py

    - name: Test ingested zerox document
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_scripts.py test_ingested_zerox_document
