[auth]
provider = "None"

[database]
provider = "None"

[kg]
provider = "neo4j"
batch_size = 256
kg_extraction_prompt = "graphrag_triplet_extraction_zero_shot"

  [kg.kg_creation_settings]
    entity_types = [] # if empty, all entities are extracted
    relation_types = [] # if empty, all relations are extracted
    fragment_merge_count = 4 # number of fragments to merge into a single extraction
    max_knowledge_triples = 100
    generation_config = { model = "gpt-4o-mini" } # and other params, model used for triplet extraction

  [kg.kg_enrichment_settings]
    generation_config = { model = "gpt-4o-mini" } # and other params, model used for node description and graph clustering
    leiden_params = { max_levels = 10 } # more params here: https://neo4j.com/docs/graph-data-science/current/algorithms/leiden/

  [kg.kg_search_config]
    model = "gpt-4o-mini"
