[chunking]
provider = "unstructured_local"
method = "by_title"
strategy = "auto"
chunking_strategy = "basic"
new_after_n_chars = 2_048
max_characters = 4_096 # use larger max_characters for KG construction
combine_under_n_chars = 512
overlap = 20

[auth]
provider = "None"

[database]
provider = "None"

[kg]
provider = "neo4j"
batch_size = 1

  [kg.kg_extraction_config]
  model = "gpt-4o"
  temperature = 0.1
  top_p = 1
  max_tokens_to_sample = 1_024
  stream = false
  add_generation_kwargs = { }
