[app]
# LLM used for internal operations, like deriving conversation names
fast_llm = "azure/gpt-4o-mini"

# LLM used for user-facing output, like RAG replies
quality_llm = "azure/gpt-4o"

# LLM used for ingesting visual inputs
vlm = "azure/gpt-4o-mini"

# LLM used for transcription
audio_lm = "azure/whisper"


# Reasoning model, used for `research` agent
reasoning_llm = "azure/o3-mini"
# Planning model, used for `research` agent
planning_llm = "azure/o3-mini"

[embedding]
provider = "litellm"
base_model = "azure/text-embedding-3-large"
base_dimension = 3072

[completion_embedding]
provider = "litellm"
base_model = "azure/text-embedding-3-large"
base_dimension = 3072
batch_size = 1
add_title_as_prefix = true
concurrent_request_limit = 256

[database]
  [database.limits]
  global_per_min = 10  # Small enough to test quickly
  monthly_limit = 20  # Small enough to test in one run

  [database.route_limits]
  "/v3/retrieval/search" = { route_per_min = 5, monthly_limit = 10 }

  [database.user_limits."47e53676-b478-5b3f-a409-234ca2164de5"]
  global_per_min = 2
  route_per_min = 1
