[parsing]
provider = "unstructured_api"

[chunking]
provider = "unstructured_api"

[chunking.chunking_config]

    strategy = "hi_res" # fast or hi_res
    chunking_strategy = "by_title" # by_title or recursive

# combine_under_n_chars=self.config.chunking_config.get('combine_under_n_chars', None),
# coordinates=self.config.chunking_config.get('coordinates', False),
# encoding=self.config.chunking_config.get('encoding', None),
# extract_image_block_types=self.config.chunking_config.get('extract_image_block_types', None),
# gz_uncompressed_content_type=self.config.chunking_config.get('gz_uncompressed_content_type', None),
# hi_res_model_name=self.config.chunking_config.get('hi_res_model_name', None),
# include_orig_elements=self.config.chunking_config.get('include_orig_elements', None),
# include_page_breaks=self.config.chunking_config.get('include_page_breaks', False),
# languages=self.config.chunking_config.get('languages', None),
# max_characters=self.config.chunking_config.get('max_characters', None),
# multipage_sections=self.config.chunking_config.get('multipage_sections', True),
# new_after_n_chars=self.config.chunking_config.get('new_after_n_chars', None),
# ocr_languages=self.config.chunking_config.get('ocr_languages', None),
# output_format=shared.OutputFormat.APPLICATION_JSON,
# overlap=self.config.chunking_config.get('overlap', 0),
# overlap_all=self.config.chunking_config.get('overlap_all', False),
# pdf_infer_table_structure=self.config.chunking_config.get('pdf_infer_table_structure', True),
# similarity_threshold=self.config.chunking_config.get('similarity_threshold', None),
# skip_infer_table_types=self.config.chunking_config.get('skip_infer_table_types', None),
# split_pdf_concurrency_level=self.config.chunking_config.get('split_pdf_concurrency_level', 5),
# split_pdf_page=self.config.chunking_config.get('split_pdf_page', True),
# starting_page_number=self.config.chunking_config.get('starting_page_number', None),
# strategy=self.config.chunking_config.get('strategy', shared.Strategy.AUTO),
# unique_element_ids=self.config.chunking_config.get('unique_element_ids', False),
# xml_keep_tags=self.config.chunking_config.get('xml_keep_tags', False),
