[parsing]
provider = "unstructured_api" # or unstructured_local

[chunking]
provider = "unstructured_api" # or unstructured_local
strategy = "hi_res" # fast or hi_res
chunking_strategy = "by_title" # by_title or recursive

# combine_under_n_chars=
# coordinates=
# encoding=
# extract_image_block_types=
# gz_uncompressed_content_type=
# hi_res_model_name=
# include_orig_elements=
# include_page_breaks=
# languages=
# max_characters=
# multipage_sections=
# new_after_n_chars=
# ocr_languages=
# output_format=
# overlap=
# overlap_all=
# pdf_infer_table_structure=
# similarity_threshold=
# skip_infer_table_types=
# split_pdf_concurrency_level=
# split_pdf_page=
# starting_page_number=
# strategy=
# unique_element_ids=
# xml_keep_tags=
