name: 'Run SDK Retrieval Tests'
description: 'Runs SDK retrieval tests for R2R'
runs:
  using: "composite"
  steps:
    # Ingest the sample file via the SDK for later tests
    - name: Ingest sample file (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_sdk_basic.py test_ingest_sample_file_sdk

    - name: Vector search sample file filter (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_sdk_basic.py test_vector_search_sample_file_filter_sdk

    - name: Hybrid search sample file filter (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_sdk_basic.py test_hybrid_search_sample_file_filter_sdk

    - name: RAG response sample file (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_sdk_basic.py test_rag_response_sample_file_sdk


    - name: Agent response sample file (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_sdk_basic.py test_conversation_history_sdk
