[tool.poetry]
name = "python-backend"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
r2r = "^0.2.84"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
