name: 'Start FUSE Server'
description: 'Starts the FUSE server'
runs:
  using: "composite"
  steps:
    - name: Start FUSE server
      shell: bash
      run: |
        cd py
        poetry run fuse serve --config-name=fuse_azure_with_test_limits &
        echo "Waiting for services to start..."
        sleep 30
