name: 'Start R2R Server'
description: 'Starts the R2R server'
runs:
  using: "composite"
  steps:
    - name: Start R2R server
      shell: bash
      run: |
        cd py
        export R2R_CONFIG_NAME=r2r_azure_with_test_limits

        docker build -t r2r/test .

        docker compose -f r2r/compose.yaml --project-name r2r --profile postgres up -d

        echo "Waiting for services to start..."
        sleep 30

        echo "R2R Container Logs:"
        docker logs r2r-r2r-1

        curl http://localhost:7272/v3/health || echo "Server not responding"
