name: 'Start R2R Server'
description: 'Starts the R2R server'
runs:
  using: "composite"
  steps:
    - name: Start R2R server
      shell: bash
      run: |
        cd py
        export R2R_CONFIG_NAME=r2r_azure_with_test_limits

        docker compose -f compose.yaml \
          --project-name r2r \
          --profile postgres \
          up -d

        echo "Waiting for services to start..."
        sleep 30
