from shared.api.models.base import (
    PaginatedResultsWrapper,
    ResultsWrapper,
    GenericBooleanResponse,
    GenericMessageResponse,
    WrappedBooleanResponse,
    WrappedGenericMessageResponse,
)
from shared.api.models.auth.responses import (
    TokenResponse,
    UserResponse,
    WrappedTokenResponse,
    WrappedUserResponse,
)
from shared.api.models.ingestion.responses import (
    IngestionResponse,
    UpdateResponse,
    WrappedIngestionResponse,
    WrappedListVectorIndicesResponse,
    WrappedMetadataUpdateResponse,
    WrappedUpdateResponse,
)
from shared.api.models.kg.responses import (
    KGCreationEstimationResponse,
    KGCreationResponse,
    KGDeduplicationEstimationResponse,
    KGEnrichmentEstimationResponse,
    KGEnrichmentResponse,
    KGEntityDeduplicationResponse,
    WrappedKGCommunitiesResponse,
    WrappedKGCreationResponse,
    WrappedKGEnrichmentResponse,
    WrappedKGEntitiesResponse,
    WrappedKGEntityDeduplicationResponse,
    WrappedKGTriplesResponse,
    WrappedKGTunePromptResponse,
)
from shared.api.models.management.responses import (
    AnalyticsResponse,
    AppSettingsResponse,
    CollectionResponse,
    ConversationResponse,
    DocumentChunkResponse,
    LogResponse,
    PromptResponse,
    ScoreCompletionResponse,
    ServerStats,
    UserOverviewResponse,
    WrappedAddUserResponse,
    WrappedAnalyticsResponse,
    WrappedAppSettingsResponse,
    WrappedCollectionResponse,
    WrappedCollectionsResponse,
    WrappedConversationResponse,
    WrappedConversationsResponse,
    WrappedDeleteResponse,
    # Document Responses
    WrappedDocumentResponse,
    WrappedDocumentsResponse,
    # Prompt Responses
    WrappedPromptResponse,
    WrappedPromptsResponse,
    WrappedLogResponse,
    WrappedPromptMessageResponse,
    # Chunk Responses
    WrappedDocumentChunkResponse,
    WrappedDocumentChunksResponse,
    # Conversation Responses
    WrappedMessageResponse,
    WrappedMessagesResponse,
    WrappedBranchResponse,
    WrappedBranchesResponse,
    # User Responses
    WrappedUserOverviewResponse,
    WrappedUsersOverviewResponse,
    WrappedServerStatsResponse,
    WrappedUserCollectionResponse,
    WrappedUsersInCollectionResponse,
    WrappedVerificationResult,
)
from shared.api.models.retrieval.responses import (
    CombinedSearchResponse,
    RAGAgentResponse,
    RAGResponse,
    WrappedCompletionResponse,
    WrappedDocumentSearchResponse,
    WrappedRAGAgentResponse,
    WrappedRAGResponse,
    WrappedSearchResponse,
    WrappedVectorSearchResponse,
)

__all__ = [
    # Auth Responses
    "TokenResponse",
    "UserResponse",
    "WrappedTokenResponse",
    "WrappedUserResponse",
    "WrappedVerificationResult",
    "WrappedGenericMessageResponse",
    # Ingestion Responses
    "IngestionResponse",
    "WrappedIngestionResponse",
    "WrappedUpdateResponse",
    "WrappedMetadataUpdateResponse",
    "WrappedListVectorIndicesResponse",
    "UpdateResponse",
    # Knowledge Graph Responses
    "KGCreationResponse",
    "WrappedKGCreationResponse",
    "KGEnrichmentResponse",
    "WrappedKGEnrichmentResponse",
    "KGEntityDeduplicationResponse",
    "WrappedKGEntityDeduplicationResponse",
    "WrappedKGTunePromptResponse",
    "KGCreationEstimationResponse",
    "KGDeduplicationEstimationResponse",
    "KGEnrichmentEstimationResponse",
    # Management Responses
    "PromptResponse",
    "ServerStats",
    "LogResponse",
    "AnalyticsResponse",
    "AppSettingsResponse",
    "ScoreCompletionResponse",
    "UserOverviewResponse",
    "DocumentChunkResponse",
    "CollectionResponse",
    "WrappedPromptMessageResponse",
    "WrappedServerStatsResponse",
    "WrappedLogResponse",
    "WrappedAnalyticsResponse",
    "WrappedAppSettingsResponse",
    "WrappedDocumentResponse",
    "WrappedDocumentsResponse",
    "WrappedCollectionResponse",
    "WrappedCollectionsResponse",
    "WrappedAddUserResponse",
    "WrappedUsersInCollectionResponse",
    # Conversation Responses
    "ConversationResponse",
    "WrappedConversationResponse",
    "WrappedConversationsResponse",
    # Prompt Responses
    "WrappedPromptResponse",
    "WrappedPromptsResponse",
    # Conversation Responses
    "WrappedMessageResponse",
    "WrappedMessagesResponse",
    "WrappedBranchResponse",
    "WrappedBranchesResponse",
    # Chunk Responses
    "WrappedDocumentChunkResponse",
    "WrappedDocumentChunksResponse",
    # User Responses
    "WrappedUserOverviewResponse",
    "WrappedUsersOverviewResponse",
    # Base Responses
    "PaginatedResultsWrapper",
    "ResultsWrapper",
    "GenericBooleanResponse",
    "GenericMessageResponse",
    "WrappedBooleanResponse",
    "WrappedGenericMessageResponse",
    # TODO: This needs to be cleaned up
    "WrappedUserCollectionResponse",
    "WrappedDeleteResponse",
    # Retrieval Responses
    "CombinedSearchResponse",
    "RAGResponse",
    "RAGAgentResponse",
    "WrappedDocumentSearchResponse",
    "WrappedSearchResponse",
    "WrappedVectorSearchResponse",
    "WrappedCompletionResponse",
    "WrappedRAGResponse",
    "WrappedRAGAgentResponse",
]
