name: 'Run SDK Ingestion Tests'
description: 'Runs SDK ingestion tests for R2R'
runs:
  using: "composite"
  steps:
    - name: Ingest sample file (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_cli.py test_ingest_sample_file_cli

    - name: Create the graph (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_cli.py test_kg_create_graph_sample_file_cli

    - name: Enrich the graph (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_cli.py test_kg_enrich_graph_sample_file_cli

    - name: Search over the graph (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_cli.py test_kg_search_sample_file_cli
