---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: r2r-secret
  namespace: r2r-dev
spec:
  encryptedData:
    AZURE_API_KEY: AgApV4stl3CuUG9f3Wvl5TafhIWaOMmeV9XF3qPH3qwyBdXT1sbvbODPDReG1z9JtXwwOZzzLjLw4fODUOGwN8UO65IFWZcUFt7MlwQHFFYFq7oTRI1cPQyXcwS6oFsWJICmFO++0+q5lZrv9sMF2HSoljysIUwTXnib9f3JNlgTqaSnlG0soKgL6dKCItRviS+ooAVvTGd5PvQdx235Xkfq0/q7CyibkC50n54RB2FnWLUuNVi5Pxqkwrq+sOlykvcNObjWjllVih6MGkiaxEJVas7w183+Y1CShhFnzHRyC2xTTK25ZYgawbOk+AWhGEPL/Zi0SS9/GwQVwmGP/qJ5nM5dv2WTU6dSY4ng/ESr3Qquu4zhyVpxWamKQN0R9zV0ybe8VUQUPz9FZaa2wnrjGvsFlXcpdcQGhjDJbHkywavdCqeBl9yEuFbxNNUjeMdkm/Fx+aub49rceKYYU44Ap/+6NChpF0wrCZ3fbiKh/A+qCXWbyHXzFMoSPLnuWRfdJZEnURSPn5W0cgcXr6EBCobkm+CRcZ32MkTaeL5lzYTQXlmsDcwyw9n0PH5GGlyPK+WWff6SlSEUE5o3RqVp9OyQWEZTPCGxBvw2xTbJVDYWyxJ0E/UCzlpAfZ18ggk/rWIqoJEdZMhzSGDdBdXOEs8uLk/1W8cd1lgs5lwEd8KaWWGYcdreiHUsPT25BZRYgvyd8f0T41p5DS1C90X3LsjZ3BdxQ/cIi/gDIZTFkQ==
    R2R_POSTGRES_PASSWORD: AgAqXlW76hVx9DgeTgse5+nGkgIhv6Vjuxv5ZgKnznWpeit6Kkt/VEwJZOkNOUOPMmFc/QiU96A3QASx1kPUa3rDm+g6czqb+0BNdwaFNb+tW607dRVAA0YszyZgZTmz5NPxYR08adLQkx8pEoue1MW0d00EYQEkpmQsdXoci6jlqKrm9TL2YN06MOpkGnbWQs5IAD8jEf4zTBQIoCls4R9gms6+bSf9ULgtFuL8WnPGdAhFL3Iq7DlSQekc/i/7EREIzcb2t49NSqosJz0rPMb0rAAQ7rlmzXhiDeDutAAdWhNayiK8t/J+dAlFYLBWCjrzTpfnE/g9QSvGeMcmRC7BlpjCSTqlNTWZedTIUDIoYV+Oo7eRmyTExSK7OwqumzvZSmE01X+GySJTwa/mH0cVj4vBDtN5UGLarn0GITURpJPM+KPjDs4oBW1iJk8aQog7NavcMsJzOYBMDT9xG/hE2hifMxMemff5WZHSy5Vb48AVHXk0GUIKsIyJ/nQ6R0G7qw8tfMCk1gUXeUGTvy0DKS4qRE7+20pGPK58oUKLys1G1hH0Q6BBIRk78lr9r74HfDgC60jO/9jusI5kqYYNWBlPIGp4jSqmi3sz4eudQxZt9qqfoftVH2tDwLlAt9BnFnmYB7vdibjMWs/CTV6EWSx3+s4DYgDWMsydBOcCkhGc+9QAfff0H4V3E+9ne0jPMGpkG8M4aUmGJrl4eJ8LJLlcHIA=
    R2R_POSTGRES_USER: AgCLXRRvKtViWZftG4dQKFmV8rH1+8P6Lssv4D2sMk8ylNqlNay8eHhDVpPfRevJM1Ax+nQh1RS7WLsdoMRi0OaJZQebR/NkouZ7yVjRap5GugpNgwLHywR6gQEh/Hugxr1/q0eUJEb01NRpMg1B23mHYWLG3Ernr55dwIyXht+hp/yAv/jXlGh3Bi2FOgYklG7g1Dq8/+qeSiGYHdmlvkzrzs9w51w0PZIJEzPjEPmJBwUeqZrVZpETmzZiXdQXsttKHtu9ahFNMNnYCVga+6ecLaqoATJdNzEpIsjykPQ/Hpit1Ya1D0zyUVZeyjMGWbOxYRUoxaNyjEIq9knUBzH7BDX57SRZpehGn2RmyI4q5q9ha4h9FK6WNvE+wdfHwNLrG3Bjhip8R4ydiqWvNwesDRkUHkz5qGPwNkeTO56aoYsb5KD3p14euhbPOMFX76oBxiReuYsY/1oYO0TT0DKPCLhRW9FWIEkKKp8luJ9c7vatEPugrudljk2QIxBgmEii5r5eOQK5cKvuDPZQ3aL3TuBfUEUqA49xkVpbBsSDtOYh3oD4uBKPQRuuT19Q3wbiLJ8Ya5+uEF1ba+/3qNYlq8SIOvzQbn21a4b52Y4I8btZZKFt7IHBtgz922h+09sCEQsrQU5tj7f66u4yma2E1Pl9M0gqHzffu46dooaCCXMtMkaNiA/6Zi5xbrZSyrBA4vQLRRnHK1OXNBj5BS4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app: r2r
      name: r2r-secret
      namespace: r2r-dev
