# Deployment and Service for Unstructured
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unstructured
  namespace: r2r-dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: unstructured
  template:
    metadata:
      labels:
        app: unstructured
    spec:
      containers:
      - name: unstructured
        image: ragtoriches/unst-prod
        ports:
          - containerPort: 7275

---
apiVersion: v1
kind: Service
metadata:
  name: unstructured
  namespace: r2r-dev
spec:
  ports:
  - protocol: TCP
    port: 7275
    targetPort: 7275
  selector:
    app: unstructured
