name: 'Run SDK Ingestion Tests'
description: 'Runs extended SDK retrieval tests for R2R'
runs:
  using: "composite"
  steps:

    # Ingestion Variants
    - name: Create document from file (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_create_document

    - name: Create document with raw_text (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_create_document_with_raw_text

    - name: Create document with chunks (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_create_document_with_chunks

    # Ingestion Modes
    - name: Create document with different ingestion modes (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_create_document_different_modes

    # Listing and Pagination
    - name: List documents (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_list_documents

    - name: List documents with pagination (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_list_documents_with_pagination

    - name: List document chunks (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_list_document_chunks

    # Retrieval and Download
    - name: Retrieve document (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_retrieve_document

    - name: Download document (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_download_document

    # Collections
    - name: List document collections (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_list_document_collections

    # Extraction & Searching
    - name: Extract document (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_extract_document

    # ESTIMATES HAVE BEEN TURNED OFF FOR NOW
    # - name: Extract document estimate (SDK)
    #   working-directory: ./py
    #   shell: bash
    #   run: poetry run python tests/integration/runner_documents.py test_extract_document_estimate

    - name: Search documents (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_search_documents

    - name: Extended search documents (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_search_documents_extended

    # Entities and Relationships
    - name: List entities (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_list_entities

    - name: List relationships (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_list_relationships

    # Permission and Error Handling
    - name: Extract document unauthorized (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_extract_document_unauthorized

    - name: Retrieve document not found (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_retrieve_document_not_found

    - name: Delete document non-existent (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_delete_document_non_existent

    - name: Get document collections non-superuser (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_get_document_collections_non_superuser

    - name: Access document not owned (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_access_document_not_owned

    # Deletions
    - name: Delete document (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_delete_document

    - name: Delete document by filters (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_documents.py test_delete_document_by_filter
