name: 'Setup Docker'
description: 'Sets up Docker for running R2R'
inputs:
  os:
    description: 'Operating system'
    required: true
  docker_username:
    description: 'Docker Hub username'
    required: true
  docker_password:
    description: 'Docker Hub password or token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@master
      with:
        docker_version: 20.10
        docker_buildx: true
        docker_nightly: true

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
