name: 'Run SDK Prompt Management Tests'
description: 'Runs SDK prompt management tests for R2R'
runs:
  using: "composite"
  steps:
    # First run basic prompt operations
    - name: Add prompt test (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_sdk.py test_add_prompt

    - name: Get prompt test (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_sdk.py test_get_prompt

    - name: Get all prompts test (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_sdk.py test_get_all_prompts

    - name: Update prompt test (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_sdk.py test_update_prompt

    # Then run error handling and access control tests
    - name: Prompt error handling test (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_sdk.py test_prompt_error_handling

    - name: Prompt access control test (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_sdk.py test_prompt_access_control

    # Finally run deletion test
    - name: Delete prompt test (SDK)
      working-directory: ./py
      shell: bash
      run: poetry run python tests/integration/runner_sdk.py test_delete_prompt
