name: 'Start FUSE Server'
description: 'Starts the FUSE server'
runs:
  using: "composite"
  steps:
  - name: Inspect Docker image manifests
    shell: bash
    run: |
      docker manifest inspect meltingrock/prod:latest

  - name: Start FUSE Server
    shell: bash
    run: |
      cd py
      poetry run fuse serve --docker --full --config-name=full_azure --build --image=fuse-local
