name: 'Start R2R Server'
description: 'Starts the R2R server'
runs:
  using: "composite"
  steps:
  - name: Inspect Docker image manifests
    run: |
      docker manifest inspect ragtoriches/prod:latest

  - name: Start R2R Server
    run: |
      cd py
      poetry run r2r serve --docker --full --config-name=full &
      echo "Waiting for services to start..."
      sleep 30
