# ========================================
# Hatchet API Deployment
# ========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hatchet-api
  namespace: r2r-system
  labels:
    app: hatchet-api
    component: orchestration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hatchet-api
  template:
    metadata:
      labels:
        app: hatchet-api
        component: orchestration
    spec:
      serviceAccountName: r2r-ksa

      initContainers:
        # Wait for RabbitMQ
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for RabbitMQ..."
              until nc -z rabbitmq 5672; do
                echo "RabbitMQ not ready, waiting..."
                sleep 5
              done
              echo "RabbitMQ is ready!"

      containers:
        # Cloud SQL Proxy for Hatchet database
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
          args:
            - "--structured-logs"
            - "--port=5432"
            - "r2r-full-deployment:us-central1:r2r-postgres"
          ports:
            - name: postgres
              containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          securityContext:
            runAsNonRoot: true

        # Hatchet API
        - name: hatchet-api
          image: ghcr.io/hatchet-dev/hatchet/hatchet-api:v0.54.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          env:
            # Database configuration (uses Cloud SQL proxy localhost)
            - name: DATABASE_URL
              value: "postgresql://$(HATCHET_DATABASE_POSTGRES_USERNAME):$(HATCHET_DATABASE_POSTGRES_PASSWORD)@127.0.0.1:5432/hatchet?sslmode=disable"

            # RabbitMQ configuration
            - name: DATABASE_RABBITMQ_URL
              value: "amqp://hatchet:$(HATCHET_RABBITMQ_PASSWORD)@rabbitmq:5672/"

            # Server configuration
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_URL
              value: "http://hatchet-api:8080"

            # Token configuration
            - name: SERVER_AUTH_COOKIE_SECRETS
              valueFrom:
                secretRef:
                  name: r2r-secrets
                  key: HATCHET_ADMIN_PASSWORD

          envFrom:
            - secretRef:
                name: r2r-secrets

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          livenessProbe:
            httpGet:
              path: /api/live
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /api/ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: hatchet-api
  namespace: r2r-system
  labels:
    app: hatchet-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: hatchet-api
