apiVersion: v1
kind: Service
metadata:
  name: r2r-api
  namespace: r2r-system
  labels:
    app: r2r-api
    component: backend
  annotations:
    cloud.google.com/neg: '{"ingress": true}'  # Enable NEG for better load balancing
    cloud.google.com/backend-config: '{"default": "r2r-backend-config"}'
spec:
  type: ClusterIP
  ports:
    - port: 7272
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: r2r-api
  sessionAffinity: None

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: r2r-backend-config
  namespace: r2r-system
spec:
  # Health check configuration
  healthCheck:
    checkIntervalSec: 10
    port: 7272
    type: HTTP
    requestPath: /v3/health

  # Connection draining timeout
  connectionDraining:
    drainingTimeoutSec: 30

  # Session affinity for better caching
  sessionAffinity:
    affinityType: "CLIENT_IP"
    affinityCookieTtlSec: 600

  # Timeout configuration
  timeoutSec: 300  # 5 minutes for long-running requests

  # CDN configuration (optional)
  cdn:
    enabled: false
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false

  # IAP configuration (optional - for authentication)
  iap:
    enabled: false
