---
apiVersion: v1
kind: Secret
metadata:
  name: r2r-secret
  namespace: r2r-dev
  labels:
    app: r2r
data:
  R2R_POSTGRES_USER: YW1wbGlmaWRiX2FkbWlu
  R2R_POSTGRES_PASSWORD: QW1wbGlmaVBhc3N3b3JkODU2Mzc5
  AZURE_API_KEY: Mzk3MmViNGU1MDQwNDM5NmIyM2RhN2M2NTk2YWQxZGU=
  AZURE_API_BASE: aHR0cHM6Ly9yYWphbi1tMm5xMnB5aS1jYW5hZGFlYXN0Lm9wZW5haS5henVyZS5jb20=