name: R2R Deep-Dive Integration Tests

on:
  push:
    branches:
      - dev
      - dev-minor
  pull_request:
    branches:
      - dev
      - dev-minor
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TELEMETRY_ENABLED: 'false'
      R2R_PROJECT_NAME: r2r_default

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python and install dependencies
        uses: ./.github/actions/setup-python-full
        with:
          os: "ubuntu-latest"

      - name: Setup and start Docker
        uses: ./.github/actions/setup-docker

      - name: Login Docker
        uses: ./.github/actions/login-docker
        with:
          docker_username: ${{ secrets.RAGTORICHES_DOCKER_UNAME }}
          docker_password: ${{ secrets.RAGTORICHES_DOCKER_TOKEN }}

      - name: Start R2R Full server
        uses: ./.github/actions/start-r2r-full

      - name: Run Test Zerox
        uses: ./.github/actions/run-script-zerox-tests
